### ISSUE TITLE
Why not use a shortcode instead of regex?

### ISSUE THREAD

**Issue by pamtbaau** [skinofthesoul/grav-plugin-antispam#17]
Instead of trying to find all possible valid email addresses using regex, you could use a shortcode that uses an explicit email parameter and other options. 

Examples of shortcode syntax:
```
[antispam autolink="true" icon="envelope-o"]user@domain.com[/antispam]
or 
[antispam autolink="true" icon="envelope-o" email="user@domain.com"]
```

Where `autolink=true` returns an email link `<a ...>`.

An added advantage of using shortcodes is that it can be used inside Twig templates.

**Comment by skinofthesoul** [comment]
Well, that would work of course, and solve some issues as well. However, I make websites for people who are in some cases bordering on computer illiterate. Some of my clients are in their sixties. They can ~use~ type up some text in Word, and that's about it. (Actually, one of them sends me all his texts in Excel, because he likes the programme!) So for these people the easiest solution is "just put in an email address like you usually do in an address block and the rest is automatically done by the system, no further thought or care necessary". And I do think that if I can let a machine do something that humans are not good at or don't like doing, I should hand it over to the machine.

I might make shortcodes an option… for more complex websites than my usual use cases it might be a good idea. I'll give it some thought!

**Comment by pamtbaau** [comment]
Fair enough. Good use-case for regex.
